nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api':   # <--- slash yok, doÄŸru regex bu
            allow_origin: ['http://localhost:5173']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
