version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ilac_takip_php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - ilac_takip

  nginx:
    image: nginx:alpine
    container_name: ilac_takip_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    depends_on:
      - php
    networks:
      - ilac_takip

  db:
    image: postgres:16-alpine
    container_name: ilac_takip_postgres
    environment:
      POSTGRES_DB: ilac_takip
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ilac_takip

networks:
  ilac_takip:
    driver: bridge

volumes:
  db_data: